In [1]:
import numpy as np

# Adjacency matrix
# m3 = [ 0,  0, 1]
#      [0.5, 0, 0]
#      [0.5, 1, 0]

m3 = np.matrix([[0, 0, 1],[0.5, 0, 0],[0.5, 1, 0]])
beta = 1
r = np.matrix([1,1,1]).T

for i in range(50):
    r = m3.dot(r)
    print(i+1)
    print(r)

1
[[1. ]
 [0.5]
 [1.5]]
2
[[1.5]
 [0.5]
 [1. ]]
3
[[1.  ]
 [0.75]
 [1.25]]
4
[[1.25]
 [0.5 ]
 [1.25]]
5
[[1.25 ]
 [0.625]
 [1.125]]
6
[[1.125]
 [0.625]
 [1.25 ]]
7
[[1.25  ]
 [0.5625]
 [1.1875]]
8
[[1.1875]
 [0.625 ]
 [1.1875]]
9
[[1.1875 ]
 [0.59375]
 [1.21875]]
10
[[1.21875]
 [0.59375]
 [1.1875 ]]
11
[[1.1875  ]
 [0.609375]
 [1.203125]]
12
[[1.203125]
 [0.59375 ]
 [1.203125]]
13
[[1.203125 ]
 [0.6015625]
 [1.1953125]]
14
[[1.1953125]
 [0.6015625]
 [1.203125 ]]
15
[[1.203125  ]
 [0.59765625]
 [1.19921875]]
16
[[1.19921875]
 [0.6015625 ]
 [1.19921875]]
17
[[1.19921875]
 [0.59960938]
 [1.20117188]]
18
[[1.20117188]
 [0.59960938]
 [1.19921875]]
19
[[1.19921875]
 [0.60058594]
 [1.20019531]]
20
[[1.20019531]
 [0.59960938]
 [1.20019531]]
21
[[1.20019531]
 [0.60009766]
 [1.19970703]]
22
[[1.19970703]
 [0.60009766]
 [1.20019531]]
23
[[1.20019531]
 [0.59985352]
 [1.19995117]]
24
[[1.19995117]
 [0.60009766]
 [1.19995117]]
25
[[1.19995117]
 [0.59997559]
 [1.20007324]]
26
[[1.20007324]
 [0.599975

In [2]:
print("Final PageRank: \n" + str(r))

Final PageRank: 
[[1.20000002]
 [0.59999999]
 [1.19999999]]
